{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "name": "X-Api-Key",
      "in": "header"
    }
  },
  "paths": {
    "/api/v1/projects/{project_id}/users/{user_id}/assessments": {
      "get": {
        "summary": "Get the list of assessments",
        "tags": [
          "Assessments"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "apiKey": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "user_id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Assessments presented",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/UserAssessment"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": "11234",
                  "name": "Assessment 1",
                  "status": "completed",
                  "started_at": "2019-03-04T15:47:33.570+04:00",
                  "completed_at": "2019-03-04T15:47:33.570+04:00"
                },
                {
                  "id": "11235",
                  "name": "Assessment 2",
                  "status": "completed",
                  "started_at": "2019-03-04T15:47:33.570+04:00",
                  "completed_at": "2019-03-04T15:47:33.570+04:00"
                },
                {
                  "id": "11236",
                  "name": "Assessment 3",
                  "status": "completed",
                  "started_at": "2019-03-04T15:47:33.570+04:00",
                  "completed_at": "2019-03-04T15:47:33.570+04:00"
                }
              ]
            }
          }
        }
      }
    },
    "/api/v1/projects/{project_id}/users": {
      "post": {
        "summary": "Adds a new user to the project",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "apiKey": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/NewUser"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User created",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "examples": {
              "application/json": {
                "id": 14602,
                "first_name": "Kamaru",
                "last_name": "Usman",
                "email": "marti@gmail.com",
                "created_at": "2019-03-04T15:47:33.570+04:00",
                "updated_at": "2019-03-04T15:47:33.950+04:00",
                "campaign_ids": [
                  510
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/projects/{project_id}/users/{user_id}": {
      "put": {
        "summary": "Updates user details",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "apiKey": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "user_id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UpdatedUser"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Update the user",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "examples": {
              "application/json": {
                "id": 14602,
                "first_name": "Kamaru",
                "last_name": "Usman",
                "email": "marti@gmail.com",
                "created_at": "2019-03-04T15:47:33.570+04:00",
                "updated_at": "2019-03-04T15:47:33.950+04:00",
                "campaign_ids": [
                  510
                ]
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "UserAssessment": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "started_at": {
          "type": "string",
          "x-nullable": true
        },
        "completed_at": {
          "type": "string",
          "x-nullable": true
        }
      }
    },
    "NewUser": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string",
          "x-nullable": true
        },
        "last_name": {
          "type": "string",
          "x-nullable": true
        },
        "email": {
          "type": "string",
          "required": true
        },
        "campaign_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "x-nullable": true
        }
      }
    },
    "UpdatedUser": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string",
          "x-nullable": true
        },
        "last_name": {
          "type": "string",
          "x-nullable": true
        },
        "email": {
          "type": "string",
          "x-nullable": true
        }
      }
    },
    "Campaign": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "campaign_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      }
    }
  }
}